name: uzman
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  url_launcher: ^6.2.5
  mask_text_input_formatter: ^2.9.0
  readmore: ^3.0.0
  cached_network_image: ^3.3.1

  # chat
  chat_bubbles: ^1.5.0
  audioplayers: ^6.0.0

  # carousel
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # loading
  flutter_spinkit: ^5.2.1

  # state management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # local storage
  shared_preferences: ^2.2.2

  # location
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0

  # network
  dio: ^5.4.0
  retrofit: ^4.0.3
  built_value: ^8.9.0
  json_annotation: ^4.8.1
  rxdart: ^0.27.7

  # localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # api & entity
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6
  built_value_generator: ^8.9.0
  json_serializable: ^6.7.1
  freezed: ^2.4.1

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
